<?php

namespace AppBundle\Form;

use AppBundle\Entity\UserGroup;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class UserEditType extends AbstractType{
    /** @var $entityManager EntityManager */
    private $entityManager;

    public function __construct(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event){
            $userGroups = $this->entityManager->getRepository("AppBundle:UserGroup")->findAll();

            $event->getForm()->
                add("role", ChoiceType::class, [
                    "label" => "Роль в системе",
                    "choices" => $userGroups,
                    "choice_label" => function ($userGroup){
                        /** @var $userGroup UserGroup */
                        return ($userGroup != null) ? $userGroup->getName() : "" ;
                    },
                    "choice_value" => function ($userGroup){
                        /** @var $userGroup UserGroup */
                        return ($userGroup != null) ? $userGroup->getIDUserGroup() : "" ;
                    }
                ]);
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}

